drop table IF EXISTS TABLE1;
drop table IF EXISTS TABLE12;
drop table IF EXISTS TABLE2;

create table TABLE1(
ID int,
INFO varchar(32),
);

create table TABLE12(
ID1 int,
ID2 int,
);

create table TABLE2(
ID int,
INFO varchar(32),
);
ALTER TABLE TABLE1 ALTER COLUMN ID int NOT NULL;
ALTER TABLE TABLE1 ADD CONSTRAINT PK_TABLE1  PRIMARY KEY (ID);


ALTER TABLE TABLE2 ALTER COLUMN ID int NOT NULL;
ALTER TABLE TABLE2 ADD CONSTRAINT PK_TABLE2  PRIMARY KEY (ID);

ALTER TABLE TABLE12 ADD FOREIGN KEY (ID1) REFERENCES TABLE1(ID);
ALTER TABLE TABLE12 ADD FOREIGN KEY (ID2) REFERENCES TABLE2(ID);

ALTER TABLE TABLE12 ALTER COLUMN ID1 int NOT NULL;
ALTER TABLE TABLE12 ALTER COLUMN ID2 int NOT NULL;


ALTER TABLE TABLE12 ADD CONSTRAINT PK_TABLE12  PRIMARY KEY (ID1,ID2);

INSERT INTO TABLE1 VALUES (1,'one');
INSERT INTO TABLE1 VALUES (3,'three');
INSERT INTO TABLE2 VALUES (4,'four');
INSERT INTO TABLE2 VALUES (2,'two');
INSERT INTO TABLE12 VALUES (1,2);

select* from TABLE1;

select* from TABLE2;

select* from TABLE12;